In [2]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [18]:
len(words)

32033

In [21]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
# print(stoi)
itos = {v: k for k, v in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [106]:
block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words[:5]:
    print(w)
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        print(''.join(itos[i] for i in context),' --> ', ch)
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix] # crop and append
X = torch.tensor(X)
Y = torch.tensor(Y)

emma
...  -->  e
..e  -->  m
.em  -->  m
emm  -->  a
mma  -->  .
olivia
...  -->  o
..o  -->  l
.ol  -->  i
oli  -->  v
liv  -->  i
ivi  -->  a
via  -->  .
ava
...  -->  a
..a  -->  v
.av  -->  a
ava  -->  .
isabella
...  -->  i
..i  -->  s
.is  -->  a
isa  -->  b
sab  -->  e
abe  -->  l
bel  -->  l
ell  -->  a
lla  -->  .
sophia
...  -->  s
..s  -->  o
.so  -->  p
sop  -->  h
oph  -->  i
phi  -->  a
hia  -->  .


In [105]:
X.shape, X.dtype, Y.shape, Y. dtype 

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [47]:
C = torch.randn((27, 2))

In [104]:
C[X].shape

torch.Size([32, 3, 2])

In [123]:
# example on how pytorch indexing works. C[X]
eg = torch.tensor([[0, 0, 1],[0, 1, 1]])
print('eg.shape:  ', eg.shape)
print('C[eg].shape', C[eg].shape)
C[eg]

eg.shape:   torch.Size([2, 3])
C[eg].shape torch.Size([2, 3, 2])


tensor([[[-0.6108,  0.0158],
         [-0.6108,  0.0158],
         [-1.2004,  2.6672]],

        [[-0.6108,  0.0158],
         [-1.2004,  2.6672],
         [-1.2004,  2.6672]]])

In [125]:
C[X][13, 2]

tensor([-1.2004,  2.6672])

In [126]:
X[13, 2]

tensor(1)

In [131]:
# C[X][13, 2] = C[X[13, 2]]
C[1]

tensor([-1.2004,  2.6672])

In [132]:
# embedd all of the integers in X
emb =  C[X]
emb.shape

torch.Size([32, 3, 2])